name: depth_camera_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.3
  - opencv=4.5.5.64
  - pyqt=5.15.9
  - pip:
      - torch==2.0.1
      - transformers==4.29.2
      - ultralytics==8.0.20
      - timm==0.9.2
